### ISSUE TITLE
Add a main function to ifs.py to make it usable as standalone program

### ISSUE THREAD

**Issue by fisyher** [windyfairy/gitadora-customs#2]
Your tools have been very useful except for ifs.py which cannot be used as a standalone program unlike the other tools such as wavbintool.py. 

As such, I have added a main function to ifs.py as in the attached file. (Enhancement request)
[ifs.txt](https://github.com/windyfairy/gitadora-customs/files/2273175/ifs.txt)

**Comment by windyfairy** [comment]
The reason I didn't add a main to ifs.py is because it's the same thing as using ifstools directly.

If you install ifstools through pip then you can run ifstools as a standalone program outside of Python (just type `ifstools` in your command prompt).
