### ISSUE TITLE
Add conversion of Guitar Hold-notes from seq to dtx

### ISSUE THREAD

**Issue by fisyher** [windyfairy/gitadora-customs#4]
Recently, Dtxmania AL has finally added the Hold-Note feature for Guitar charts in v052 (31st Jan 2019) [http://senamih.com/dtxal/](url) 
I took a look into how this hold-note is stored in the .dtx file format:

- Hold-Note lane code is 2C e.g. #0012C: 01000001
- Has two types of markers: StartHold and EndHold. 
- Start Hold must coincide exactly with a note that has button pressed; EndHold must never coincide with any notes. 
- No other notes in between StartHold and EndHold markers are allowed. If there are notes present, the hold-note will not appear in-game
- Value of markers does not seem to matter.

Requesting to add this as feature enhancement for seq to dtx conversion.

**Comment by windyfairy** [comment]
Thanks for the heads up! I had someone mention this in passing a week or so ago but I didn't look into the details yet. I'll try to get his supported once I finish refactoring another project I'm working on.

Thanks for including the specifics. I already have code to handle hold notes when converting to DTX, but it was based on an old proposed extension to DTXMania that used 2A for guitar and 2B for bass. This is also supported by some versions of DTXCreator but it's really hacky.

It looks like the version of DTXMania you linked is using 2C for guitar and 2D for bass.

If you would like to test the functionality, change 2A to 2C and 2B to 2D in the following areas:
https://github.com/windyfairy/gitadora-customs/blob/master/plugins/dtx.py#L596
https://github.com/windyfairy/gitadora-customs/blob/master/plugins/dtx.py#L611
https://github.com/windyfairy/gitadora-customs/blob/master/plugins/dtx.py#L2279
https://github.com/windyfairy/gitadora-customs/blob/master/plugins/dtx.py#L1408
https://github.com/windyfairy/gitadora-customs/blob/master/plugins/dtx.py#L1425

**Comment by windyfairy** [comment]
@fisyher I've added support for long notes as per DTXMania AL specs and tested it with a few songs. If you find any bugs please create a new issue and I'll handle it separately.
