### ISSUE TITLE
Some guitar chart converted from sq3 to dtx have drum key sounds

### ISSUE THREAD

**Issue by fisyher** [windyfairy/gitadora-customs#6]
Some songs when converted from sq3 to dtx using seqtool.py have drum key sounds playing in their guitar dtx. (Sounds really awful to the ear with random cymbals and toms playing in guitar mode)
Songs that have this issue have ID: 403, 600. There could be more.

Opening the converted dtx with an editor shows these drum wav files have low numbers in their filename like 0024.wav, 0025.wav to 0033.wav whereas guitar wav files are all at least 01xx.wav. 

I believe there are unintentional file overwrites during bin to wav conversion process. Please take a look into this.

**Comment by windyfairy** [comment]
I am in the process of completely rewriting the tool, and as such the old code won't be updated anymore so I'm going to close this.

If the new version of the code (you'll know when it gets pushed) still has the same bugs then please reopen at a later date.
