### ISSUE TITLE
Key sounds volume values does not match values inside metadata.json

### ISSUE THREAD

**Issue by fisyher** [windyfairy/gitadora-customs#7]
When converting some sq3 to dtx for guitar and bass notes, the dtx converted from sq3 have very loud key sounds. It seems the VOLUME values for key sounds are almost always set to 100 despite the metadata.json on key sounds  

After some digging in dtx.py, I found this 2 lines 2209 and 2210:

```
volume = 127  # 100% volume
volume_final = 100
```

These 2 lines will always overwrite whatever value that is read from metadata to the volume variable in line 2191. I do not think this is intentional. Maybe you should shift the 2 lines above line 2191?

**Comment by windyfairy** [comment]
I am in the process of completely rewriting the tool, and as such the old code won't be updated anymore so I'm going to close this.

If the new version of the code (you'll know when it gets pushed) still has the same bugs then please reopen at a later date.
